# Generated by Django 6.0.1 on 2026-01-15 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('skin_test_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_mixes', models.IntegerField(db_index=True, default=0)),
                ('last_visit_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_appointment_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_user', models.ForeignKey(blank=True, help_text='Staff member who created/manages this client (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='authapp.subuser')),
                ('user', models.ForeignKey(help_text='Salon owner who owns this client', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After')], db_index=True, max_length=10)),
                ('image', models.ImageField(help_text='Client before/after photo', upload_to='client_images/%Y/%m/%d/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clientapp.client')),
            ],
            options={
                'db_table': 'client_images',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'name'], name='clients_user_id_21b477_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['sub_user', 'name'], name='clients_sub_use_99b315_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'last_visit_date'], name='clients_user_id_c1364f_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'next_appointment_date'], name='clients_user_id_24963e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name', 'email'], name='clients_name_f83e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='clientimage',
            index=models.Index(fields=['client', 'image_type'], name='client_imag_client__a5924e_idx'),
        ),
        migrations.AddIndex(
            model_name='clientimage',
            index=models.Index(fields=['client', 'upload_date'], name='client_imag_client__0f65e6_idx'),
        ),
    ]
