# Generated by Django 6.0.1 on 2026-01-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Client profile photo', null=True, upload_to='client_profiles/%Y/%m/%d/'),
        ),
    ]
