# Generated by Django 6.0.1 on 2026-02-07 10:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retailerapp', '0003_retailerprofile_stripe_account_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retailerapp.customerdeliveryaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRetailerSplit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('platform_fee_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_splits', to='paymentapp.payment')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_splits', to='retailerapp.retailerprofile')),
            ],
            options={
                'db_table': 'payment_retailer_splits',
            },
        ),
    ]
