# Generated by Django 6.0.1 on 2026-02-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0007_expense'),
        ('paymentapp', '0002_alter_payment_payment_intent_id'),
        ('retailerapp', '0004_retailerprofile_api_key_retailerprofile_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_address_label', models.CharField(max_length=50)),
                ('delivery_full_address', models.TextField()),
                ('delivery_area', models.CharField(max_length=255)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_orders', to='paymentapp.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mixapp.shopproduct')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='retailerapp.retailerprofile')),
            ],
            options={
                'db_table': 'retailer_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['retailer', '-created_at'], name='retailer_or_retaile_06baf5_idx'), models.Index(fields=['payment', 'retailer'], name='retailer_or_payment_70d91e_idx'), models.Index(fields=['status'], name='retailer_or_status_f356a1_idx')],
            },
        ),
    ]
