# Generated by Django 6.0.1 on 2026-02-05 06:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mixapp', '0005_shopproduct_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(db_index=True, help_text='Official business/shop name', max_length=255)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard delivery charge', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount for free delivery', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_orders', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_pending', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_cancelled', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text="Links to User with role='retailer'", on_delete=django.db.models.deletion.CASCADE, related_name='retailer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retailer_profiles',
            },
        ),
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(db_index=True, help_text='e.g., Gulshan, Dhanmondi, Banani', max_length=255)),
                ('postal_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('custom_delivery_charge', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use retailer's default charge", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_areas', to='retailerapp.retailerprofile')),
            ],
            options={
                'db_table': 'delivery_areas',
            },
        ),
        migrations.CreateModel(
            name='CustomerDeliveryAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_label', models.CharField(help_text='e.g., Home, Office, Salon', max_length=50)),
                ('full_address', models.TextField()),
                ('area', models.CharField(db_index=True, help_text='Must match DeliveryArea.area_name for delivery', max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default shipping address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_delivery_addresses',
                'indexes': [models.Index(fields=['user', 'is_default'], name='customer_de_user_id_8848bf_idx'), models.Index(fields=['area'], name='customer_de_area_f5b449_idx')],
            },
        ),
        migrations.CreateModel(
            name='MissingProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('added', 'Added to Catalog'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missing_product_requests', to='mixapp.shopproduct')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_product_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'missing_products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', 'status'], name='missing_pro_request_d14c49_idx'), models.Index(fields=['status', '-created_at'], name='missing_pro_status_665145_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='retailerprofile',
            index=models.Index(fields=['user'], name='retailer_pr_user_id_c235b4_idx'),
        ),
        migrations.AddIndex(
            model_name='retailerprofile',
            index=models.Index(fields=['business_name'], name='retailer_pr_busines_829e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryarea',
            index=models.Index(fields=['retailer', 'is_active'], name='delivery_ar_retaile_435da6_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryarea',
            index=models.Index(fields=['area_name'], name='delivery_ar_area_na_730d3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryarea',
            constraint=models.UniqueConstraint(fields=('retailer', 'area_name'), name='unique_retailer_area'),
        ),
    ]
