# Generated by Django 6.0.1 on 2026-02-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdeliveryaddress',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, help_text='Default shipping address', null=True),
        ),
    ]
