# Generated by Django 6.0.1 on 2026-02-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailerapp', '0002_alter_customerdeliveryaddress_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account ID', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='stripe_connected',
            field=models.BooleanField(default=False, help_text='Is Stripe onboarding complete?'),
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='stripe_connection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
