# Generated by Django 6.0.1 on 2026-02-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailerapp', '0003_retailerprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for retailer integrations', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status - must be True to login'),
        ),
    ]
