# Generated by Django 6.0.1 on 2026-02-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailerapp', '0004_retailerprofile_api_key_retailerprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='business_logo',
            field=models.ImageField(blank=True, help_text='Business logo image', null=True, upload_to='retailer_logos/'),
        ),
    ]
