# Generated by Django 6.0.1 on 2026-03-09 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailerapp', '0005_retailerprofile_business_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products_affected', models.IntegerField(default=0)),
                ('products_skipped', models.IntegerField(default=0, help_text='Products skipped due to price too low')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_logs', to='retailerapp.retailerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
