# Generated by Django 5.2.12 on 2026-03-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailerapp', '0006_discountlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
