# Generated by Django 6.0.1 on 2026-01-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
