# Generated by Django 6.0.1 on 2026-02-14 04:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_subuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available commission for withdrawal', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='has_active_subscription',
            field=models.BooleanField(default=False, help_text='Does user have active subscription?'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='When subscription expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_commission_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total commission earned from referrals', max_digits=10),
        ),
    ]
