"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import stripe
from typing import Dict, Any , List

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=$mj0-4$vzl@vu453-#1tf51c6&pe%kaf)j^8qjh(*s!@1gm)k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'adminapp', 
    'authapp',
    'clientapp',
    'mixapp',
    'appointmentapp',
    'retailerapp',  # ✅ ADD THIS
    'paymentapp',
    'affiliateapp',
    # 'productapp',
    'privacypolicyapp',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
       # 'myproject.middleware.SubscriptionMiddleware',  # ❌ Comment this out for now
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES: List[Dict[str, Any]]  = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [BASE_DIR / 'retailerapp' / 'templates'],  # ✅ ADD THIS
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES : Dict[str, Dict[str, Any]] = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CSRF_TRUSTED_ORIGINS = [
        'https://6zpmb4x8-8015.inc1.devtunnels.ms/',
        "http://localhost:8015",
]
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



CORS_ALLOW_ALL_ORIGINS = True#allowing all the different origins 
CORS_ALLOW_CREDENTIALS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# REST Framework configuration
REST_FRAMEWORK : Dict[str, Any] = {
    # Default authentication classes
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
    # Default permission classes
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ],
    
    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    
    # Filtering
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    
    # Throttling (rate limiting)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Anonymous users
        'user': '1000/hour',  # Authenticated users
    },
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# Cache configuration (using Redis for production)
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'KEY_PREFIX': 'serviceconnect',
#         'TIMEOUT': 3600,  # 1 hour default timeout
#     }
# }
'''
✅ Advantages of using Redis for caching

-Much faster than hitting the database every time

-Reduces database load → improves performance under traffic

-Stores data in memory, so responses are almost instant

-Perfect for storing frequently requested data (dashboard stats, lists, tokens, etc.)

❌ What happens if you don’t use Redis?

-Every request will hit the database directly

-Your app becomes slower, especially under high traffic

-Higher chance of database overload

-Poor performance for pages that need repeated calculations/queries

-Redis = speed + reduced DB cost + better scalability.
'''


# Example configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',  # Unique name for cache
    }
}

SIMPLE_JWT : Dict[str, Any] = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=43200),  # Access token validity-30 days
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # Refresh token validity
    'AUTH_HEADER_TYPES': ('Bearer',),  # JWT header type
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,  # Enable blacklisting
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}


# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# # EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'mdtm20062@gmail.com'  # my Gmail account
# EMAIL_HOST_PASSWORD = 'gvcumgjelpftdsgb'
# DEFAULT_FROM_EMAIL = 'MY COLOR COST'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'ops@mycolourcost.com'
EMAIL_HOST_PASSWORD = 'LouisJedDevPatel123!'

DEFAULT_FROM_EMAIL = 'MY COLOR COST <ops@mycolourcost.com>'
#==================================================================================/

STATIC_ROOT = BASE_DIR / 'staticfiles'  # or your preferred location


AUTH_USER_MODEL = 'authapp.User'#Since you're using a custom User model, make sure you've also set this in your settings.py:


""
STRIPE_SECRET_KEY = "sk_test_51SJRZxHPckdqCiP923JxGvV19Hjo8PBdG9CLbIvpOKYMrozDGoPsoXDgbJjPFrlRmOj3eRIAhsUv2Ztxj2xCqXBX00GbEMdfiO" # from your Stripe dashboard
STRIPE_PUBLIC_KEY = "pk_test_51SJRZxHPckdqCiP90dDxnY7aqJLHWMRbX6hOxHVWnPmnmMzGljcXl5BF3CWwdsQDedCpC6odOm5OuEw9zYJ8m6El00l7mKiOUW" 

stripe.api_key = STRIPE_SECRET_KEY

STRIPE_WEBHOOK_SECRET='whsec_vMDymKpbvdeU5BWuD0EVY9ZK8GK98YAq' # I got it from stripe dashboard, which is smaller

STRIPE_PLATFORM_FEE_PERCENT = 5

BASE_URL = "https://6zpmb4x8-8015.inc1.devtunnels.ms"

# BASE_URL = "http://10.10.12.14:8000"
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "6zpmb4x8-8015.inc1.devtunnels.ms",
    '*',
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


BARCODE_SPIDER_API_KEY = 'c7942a6929183658052f'
BARCODE_SPIDER_BASE_URL = 'https://api.barcodespider.com/v1'















