# Generated by Django 6.0.1 on 2026-01-21 10:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
        ('clientapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mix_name', models.CharField(db_index=True, max_length=255)),
                ('service_type', models.CharField(db_index=True, max_length=100)),
                ('charged_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount charged to client', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of products used', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit = charged_amount - total_cost', max_digits=10)),
                ('created_date', models.DateField(db_index=True)),
                ('created_time', models.TimeField()),
                ('pdf_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client this mix is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mixes', to='clientapp.client')),
                ('sub_user', models.ForeignKey(blank=True, help_text='Staff member who created (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixes', to='authapp.subuser')),
                ('user', models.ForeignKey(help_text='Salon owner', on_delete=django.db.models.deletion.CASCADE, related_name='mixes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mixes',
                'ordering': ['-created_date', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_products/')),
                ('market_price', models.DecimalField(decimal_places=2, help_text='Market price per 100g', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_reviews', models.IntegerField(default=0)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Barcode for scanning', max_length=100, null=True, unique=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shop_products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='shop_produc_name_fa7455_idx'), models.Index(fields=['barcode'], name='shop_produc_barcode_e43b3e_idx'), models.Index(fields=['average_rating'], name='shop_produc_average_62e30a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='mixapp.shopproduct')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductScanHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('scanned_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scan_type', models.CharField(choices=[('barcode', 'Barcode'), ('qr', 'QR Code'), ('manual', 'Manual Entry')], default='barcode', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL)),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to='mixapp.shopproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating between 1 and 5', validators=[django.core.validators.MinValueValidator(1)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mixapp.shopproduct')),
            ],
            options={
                'db_table': 'product_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_price', models.DecimalField(decimal_places=2, help_text="User's custom price per 100g", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_weight_grams', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available weight in grams', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Is product currently available for use')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='mixapp.shopproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_products',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='MixProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('used_weight', models.DecimalField(decimal_places=2, help_text='Weight used in grams', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('market_price', models.DecimalField(decimal_places=2, help_text='Market price per 100g at time of use', max_digits=10)),
                ('user_price', models.DecimalField(decimal_places=2, help_text="User's price per 100g at time of use", max_digits=10)),
                ('each_item_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost for this item', max_digits=10)),
                ('is_bleach_timer_on', models.BooleanField(default=False)),
                ('bleach_timer_started_at', models.CharField(blank=True, max_length=50, null=True)),
                ('bleach_timer_duration', models.CharField(blank=True, help_text='e.g. 30 min, 1 hour', max_length=30, null=True)),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_products', to='mixapp.mix')),
                ('user_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_products', to='mixapp.userproduct')),
            ],
            options={
                'db_table': 'mix_products',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='mix',
            index=models.Index(fields=['user', 'created_date'], name='mixes_user_id_242b64_idx'),
        ),
        migrations.AddIndex(
            model_name='mix',
            index=models.Index(fields=['client', 'created_date'], name='mixes_client__0b695c_idx'),
        ),
        migrations.AddIndex(
            model_name='mix',
            index=models.Index(fields=['service_type'], name='mixes_service_973b63_idx'),
        ),
        migrations.AddIndex(
            model_name='mix',
            index=models.Index(fields=['-created_date', '-created_time'], name='mixes_created_c37e03_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['user', 'added_at'], name='mixapp_shop_user_id_ddad0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('user', 'shop_product')},
        ),
        migrations.AddIndex(
            model_name='productscanhistory',
            index=models.Index(fields=['user', 'created_at'], name='mixapp_prod_user_id_b6fabe_idx'),
        ),
        migrations.AddIndex(
            model_name='productscanhistory',
            index=models.Index(fields=['shop_product', 'created_at'], name='mixapp_prod_shop_pr_2bc1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='productscanhistory',
            index=models.Index(fields=['created_at'], name='mixapp_prod_created_e08b46_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', '-created_at'], name='product_rev_product_b958dd_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user'], name='product_rev_user_id_f1d802_idx'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_review'),
        ),
        migrations.AddIndex(
            model_name='userproduct',
            index=models.Index(fields=['user', 'is_available'], name='user_produc_user_id_c4b752_idx'),
        ),
        migrations.AddIndex(
            model_name='userproduct',
            index=models.Index(fields=['user', 'product'], name='user_produc_user_id_050ed8_idx'),
        ),
        migrations.AddConstraint(
            model_name='userproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product'),
        ),
        migrations.AddIndex(
            model_name='mixproduct',
            index=models.Index(fields=['mix'], name='mix_product_mix_id_26b71a_idx'),
        ),
        migrations.AddIndex(
            model_name='mixproduct',
            index=models.Index(fields=['user_product'], name='mix_product_user_pr_b51d97_idx'),
        ),
    ]
