# Generated by Django 6.0.1 on 2026-01-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mixproduct',
            old_name='bleach_timer_started_at',
            new_name='bleach_timer_start_time',
        ),
    ]
