# Generated by Django 6.0.1 on 2026-01-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode for scanning', max_length=100, null=True, unique=True),
        ),
    ]
