# Generated by Django 6.0.1 on 2026-01-28 06:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0002_rename_bleach_timer_started_at_mixproduct_bleach_timer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='user_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="User's custom price per 100g", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
