# Generated by Django 6.0.1 on 2026-01-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0003_alter_userproduct_user_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='api_data',
            field=models.JSONField(blank=True, help_text='Full API response from Barcode Spider', null=True),
        ),
    ]
