# Generated by Django 6.0.1 on 2026-02-05 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0004_shopproduct_api_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Available stock quantity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
