# Generated by Django 6.0.1 on 2026-02-05 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0005_shopproduct_quantity'),
        ('retailerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='retailer',
            field=models.ForeignKey(blank=True, help_text='Retailer selling this product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='retailerapp.retailerprofile'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('low_stock', 'Low Stock')], db_index=True, default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='mixproduct',
            name='is_bleach_timer_on',
            field=models.BooleanField(default=True),
        ),
    ]
