# Generated by Django 6.0.1 on 2026-02-28 04:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0007_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='VAT percentage (e.g., 15.00 means 15%)', max_digits=5, null=True),
        ),
    ]
