# Generated by Django 6.0.1 on 2026-03-11 09:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0008_shopproduct_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='discounted_market_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price after discount. None means no discount active', max_digits=10, null=True),
        ),
    ]
