# Generated by Django 6.0.1 on 2026-03-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0009_shopproduct_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='promo_buy_quantity',
            field=models.IntegerField(blank=True, help_text='Buy this many (e.g. 5 for buy-5-get-1-free)', null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='promo_free_quantity',
            field=models.IntegerField(blank=True, help_text='Get this many free (e.g. 1 for buy-5-get-1-free)', null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='promo_is_active',
            field=models.BooleanField(default=False, help_text='Is this promo currently active?'),
        ),
    ]
