# Generated by Django 6.0.1 on 2026-03-14 09:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0010_shopproduct_promo_buy_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='original_weight_grams',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original weight when product was first added', max_digits=10),
        ),
    ]
