# Generated by Django 5.2.12 on 2026-03-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixapp', '0011_userproduct_original_weight_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
