# Generated by Django 6.0.1 on 2026-03-03 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Full terms and conditions text')),
                ('version', models.CharField(default='1.0', help_text='e.g. 1.0, 1.1, 2.0', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active terms should exist at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Superuser who last updated the terms', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms and Conditions',
                'verbose_name_plural': 'Terms and Conditions',
                'db_table': 'terms_and_conditions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
