# Generated by Django 6.0.1 on 2026-03-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacypolicyapp', '0002_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='type',
            field=models.CharField(choices=[('app', 'App'), ('retailer', 'Retailer')], default='app', max_length=20),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='type',
            field=models.CharField(choices=[('app', 'App'), ('retailer', 'Retailer')], default='app', max_length=20),
        ),
    ]
