# Generated by Django 6.0.1 on 2026-02-04 04:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0002_alter_subuser_is_active'),
        ('clientapp', '0002_client_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Service name (e.g., Haircut, Coloring, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_types',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField(help_text='Daily start time (e.g., 09:00 AM)')),
                ('end_time', models.TimeField(help_text='Daily end time (e.g., 08:00 PM)')),
                ('off_days', models.CharField(blank=True, default='', help_text='Comma-separated weekday numbers (0=Monday, 6=Sunday)', max_length=20)),
                ('is_locked', models.BooleanField(default=True, help_text='Once set, working hours cannot be changed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Working Hours',
                'db_table': 'working_hours',
            },
        ),
        migrations.CreateModel(
            name='AppointmentURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='Unique URL token for booking page', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='URL can be deactivated to stop accepting bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_url', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment_urls',
                'indexes': [models.Index(fields=['token'], name='appointment_token_dfb834_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, help_text='Client name (for self-booking)', max_length=255, null=True)),
                ('client_contact', models.CharField(blank=True, help_text='Client contact number (for self-booking)', max_length=20, null=True)),
                ('client_email', models.EmailField(blank=True, help_text='Client email (for self-booking)', max_length=254, null=True)),
                ('appointment_date', models.DateField(db_index=True, help_text='Date of appointment')),
                ('appointment_time', models.TimeField(db_index=True, help_text='Time of appointment (15-min intervals)')),
                ('appointment_type', models.CharField(choices=[('manual', 'Manual (Created by Owner/Staff)'), ('self_booked', 'Self-Booked (Client via URL)')], db_index=True, default='manual', help_text='How this appointment was created', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20)),
                ('reminder_hours', models.IntegerField(blank=True, help_text='Send reminder X hours before appointment', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('reminder_sent', models.BooleanField(default=False, help_text='Track if reminder email was sent')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about appointment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Existing client (manual booking only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clientapp.client')),
                ('sub_user', models.ForeignKey(blank=True, help_text='Staff member handling this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='authapp.subuser')),
                ('user', models.ForeignKey(help_text='Salon owner who owns this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(blank=True, help_text='Type of service requested', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointmentapp.servicetype')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['user', 'appointment_date', 'appointment_time'], name='appointment_user_id_7dd66e_idx'), models.Index(fields=['user', 'status'], name='appointment_user_id_9e7c3d_idx'), models.Index(fields=['client', 'appointment_date'], name='appointment_client__d164fb_idx'), models.Index(fields=['appointment_date', 'appointment_time', 'status'], name='appointment_appoint_9a247a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeSlotBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('time_slot', models.TimeField(db_index=True)),
                ('current_bookings', models.IntegerField(default=0, help_text='Current number of bookings for this slot', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_capacity', models.IntegerField(help_text='Max bookings allowed (team_size for owner, 1 for self_employed)', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_full', models.BooleanField(db_index=True, default=False, help_text='True when current_bookings >= max_capacity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'time_slot_bookings',
                'indexes': [models.Index(fields=['user', 'date', 'is_full'], name='time_slot_b_user_id_81ef24_idx'), models.Index(fields=['date', 'time_slot'], name='time_slot_b_date_68846a_idx')],
                'unique_together': {('user', 'date', 'time_slot')},
            },
        ),
    ]
