# Generated by Django 6.0.1 on 2026-02-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_name',
            field=models.CharField(blank=True, help_text='Service name (for manual booking - free text)', max_length=100),
        ),
    ]
